### ISSUE TITLE
broken link in TOC

### ISSUE THREAD

**Issue by epogrebnyak** [psibi/fakedata#10] opened 2020-02-17 09:39 UTC
Reading Haddock Documentation in README.md points to non-existent link, maybe delete it?

**Comment by psibi** [comment] 2020-02-17 10:15
@epogrebnyak Thanks for filing the issue. But I think the issue is more with how haddock handles the link.  You can see the same link will work here: https://github.com/psibi/fakedata#readme

**Comment by epogrebnyak** [comment] 2020-02-17 10:27
I'm simply looking to README.md TOC, it has:

```
[Reading Haddock Documentation](#reading-haddock-documentation)
```

but there is no anchor `#reading-haddock-documentation` in README.md, so it is a brocken link.
Maybe you wanted to point it to somewhere else?

>  You can see the same link will work here: https://github.com/psibi/fakedata#readme

The link does not work there either.

**Comment by psibi** [comment] 2020-02-17 11:28
@epogrebnyak Nice Catch! Yeah, that's a broken link. Free feel to send a MR. If not, I will fix this by the coming weekend. Thanks.

**Comment by epogrebnyak** [comment] 2020-02-17 11:41
No PR for this, sorry. Should be easy to delete line from a github web
form.

пн, 17 февр. 2020 г., 14:28 Sibi <notifications@github.com>:

**Comment by psibi** [comment] 2020-02-29 05:07
Fixed in master.

**Closed by psibi** 2020-02-29 05:07 UTC
